# -*- coding: utf-8 -*-
"""
Created on Wen Feb 5 10:57:48 2020

@author: Gaston A. Nuñez - ingenganu@gmail.com
"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1065, 549)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 501, 301))
        self.groupBox.setObjectName("groupBox")
        self.pushButtonConnectIOT = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonConnectIOT.setGeometry(QtCore.QRect(354, 270, 121, 23))
        self.pushButtonConnectIOT.setObjectName("pushButtonConnectIOT")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 458, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelHost = QtWidgets.QLabel(self.layoutWidget)
        self.labelHost.setMinimumSize(QtCore.QSize(50, 0))
        self.labelHost.setObjectName("labelHost")
        self.horizontalLayout.addWidget(self.labelHost)
        self.lineEditHostIOT = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditHostIOT.sizePolicy().hasHeightForWidth())
        self.lineEditHostIOT.setSizePolicy(sizePolicy)
        self.lineEditHostIOT.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditHostIOT.setObjectName("lineEditHostIOT")
        self.horizontalLayout.addWidget(self.lineEditHostIOT)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 60, 458, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelPort = QtWidgets.QLabel(self.layoutWidget1)
        self.labelPort.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPort.setObjectName("labelPort")
        self.horizontalLayout_2.addWidget(self.labelPort)
        self.lineEditPortIOT = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPortIOT.sizePolicy().hasHeightForWidth())
        self.lineEditPortIOT.setSizePolicy(sizePolicy)
        self.lineEditPortIOT.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPortIOT.setObjectName("lineEditPortIOT")
        self.horizontalLayout_2.addWidget(self.lineEditPortIOT)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 90, 458, 24))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelPortClientId = QtWidgets.QLabel(self.layoutWidget_3)
        self.labelPortClientId.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPortClientId.setObjectName("labelPortClientId")
        self.horizontalLayout_4.addWidget(self.labelPortClientId)
        self.lineEditPortClientId = QtWidgets.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPortClientId.sizePolicy().hasHeightForWidth())
        self.lineEditPortClientId.setSizePolicy(sizePolicy)
        self.lineEditPortClientId.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPortClientId.setObjectName("lineEditPortClientId")
        self.horizontalLayout_4.addWidget(self.lineEditPortClientId)
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_8.setGeometry(QtCore.QRect(20, 210, 458, 24))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.labelPortUserName = QtWidgets.QLabel(self.layoutWidget_8)
        self.labelPortUserName.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPortUserName.setObjectName("labelPortUserName")
        self.horizontalLayout_14.addWidget(self.labelPortUserName)
        self.lineEditPortUserNameI = QtWidgets.QLineEdit(self.layoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPortUserNameI.sizePolicy().hasHeightForWidth())
        self.lineEditPortUserNameI.setSizePolicy(sizePolicy)
        self.lineEditPortUserNameI.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPortUserNameI.setText("")
        self.lineEditPortUserNameI.setObjectName("lineEditPortUserNameI")
        self.horizontalLayout_14.addWidget(self.lineEditPortUserNameI)
        self.layoutWidget_14 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_14.setGeometry(QtCore.QRect(20, 240, 458, 24))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.labelPort_12 = QtWidgets.QLabel(self.layoutWidget_14)
        self.labelPort_12.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPort_12.setObjectName("labelPort_12")
        self.horizontalLayout_21.addWidget(self.labelPort_12)
        self.lineEditPortPassword = QtWidgets.QLineEdit(self.layoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPortPassword.sizePolicy().hasHeightForWidth())
        self.lineEditPortPassword.setSizePolicy(sizePolicy)
        self.lineEditPortPassword.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPortPassword.setText("")
        self.lineEditPortPassword.setObjectName("lineEditPortPassword")
        self.horizontalLayout_21.addWidget(self.lineEditPortPassword)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 120, 330, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBoxCleanSession = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBoxCleanSession.setObjectName("checkBoxCleanSession")
        self.horizontalLayout_8.addWidget(self.checkBoxCleanSession)
        self.checkBoxAutoConnect = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBoxAutoConnect.setObjectName("checkBoxAutoConnect")
        self.horizontalLayout_8.addWidget(self.checkBoxAutoConnect)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelPortKeepAlive = QtWidgets.QLabel(self.layoutWidget2)
        self.labelPortKeepAlive.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPortKeepAlive.setObjectName("labelPortKeepAlive")
        self.horizontalLayout_7.addWidget(self.labelPortKeepAlive)
        self.spinBoxKeepAlive = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBoxKeepAlive.setObjectName("spinBoxKeepAlive")
        self.horizontalLayout_7.addWidget(self.spinBoxKeepAlive)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 160, 461, 30))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelTopicSub = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTopicSub.sizePolicy().hasHeightForWidth())
        self.labelTopicSub.setSizePolicy(sizePolicy)
        self.labelTopicSub.setMinimumSize(QtCore.QSize(50, 0))
        self.labelTopicSub.setObjectName("labelTopicSub")
        self.horizontalLayout_3.addWidget(self.labelTopicSub)
        self.comboBoxSubTopics = QtWidgets.QComboBox(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSubTopics.sizePolicy().hasHeightForWidth())
        self.comboBoxSubTopics.setSizePolicy(sizePolicy)
        self.comboBoxSubTopics.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxSubTopics.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBoxSubTopics.setEditable(True)
        self.comboBoxSubTopics.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBoxSubTopics.setObjectName("comboBoxSubTopics")
        self.comboBoxSubTopics.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBoxSubTopics)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 340, 1031, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textBrowserReceived = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowserReceived.setGeometry(QtCore.QRect(10, 30, 1001, 101))
        self.textBrowserReceived.setObjectName("textBrowserReceived")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(540, 20, 501, 301))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButtonConnectDB = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonConnectDB.setGeometry(QtCore.QRect(354, 270, 121, 23))
        self.pushButtonConnectDB.setObjectName("pushButtonConnectDB")
        self.layoutWidget_10 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_10.setGeometry(QtCore.QRect(20, 30, 458, 24))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labelHost_3 = QtWidgets.QLabel(self.layoutWidget_10)
        self.labelHost_3.setMinimumSize(QtCore.QSize(50, 0))
        self.labelHost_3.setObjectName("labelHost_3")
        self.horizontalLayout_13.addWidget(self.labelHost_3)
        self.lineEditHostDB = QtWidgets.QLineEdit(self.layoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditHostDB.sizePolicy().hasHeightForWidth())
        self.lineEditHostDB.setSizePolicy(sizePolicy)
        self.lineEditHostDB.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditHostDB.setObjectName("lineEditHostDB")
        self.horizontalLayout_13.addWidget(self.lineEditHostDB)
        self.layoutWidget_11 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_11.setGeometry(QtCore.QRect(20, 60, 458, 24))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.labelPort_3 = QtWidgets.QLabel(self.layoutWidget_11)
        self.labelPort_3.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPort_3.setObjectName("labelPort_3")
        self.horizontalLayout_16.addWidget(self.labelPort_3)
        self.lineEditPortDB = QtWidgets.QLineEdit(self.layoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPortDB.sizePolicy().hasHeightForWidth())
        self.lineEditPortDB.setSizePolicy(sizePolicy)
        self.lineEditPortDB.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPortDB.setObjectName("lineEditPortDB")
        self.horizontalLayout_16.addWidget(self.lineEditPortDB)
        self.layoutWidget_12 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_12.setGeometry(QtCore.QRect(20, 90, 458, 24))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.labelPortClientId_3 = QtWidgets.QLabel(self.layoutWidget_12)
        self.labelPortClientId_3.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPortClientId_3.setObjectName("labelPortClientId_3")
        self.horizontalLayout_17.addWidget(self.labelPortClientId_3)
        self.lineEditPortClientId_3 = QtWidgets.QLineEdit(self.layoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPortClientId_3.sizePolicy().hasHeightForWidth())
        self.lineEditPortClientId_3.setSizePolicy(sizePolicy)
        self.lineEditPortClientId_3.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPortClientId_3.setObjectName("lineEditPortClientId_3")
        self.horizontalLayout_17.addWidget(self.lineEditPortClientId_3)
        self.layoutWidget_13 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_13.setGeometry(QtCore.QRect(20, 210, 458, 24))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget_13)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.labelPortUserName_3 = QtWidgets.QLabel(self.layoutWidget_13)
        self.labelPortUserName_3.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPortUserName_3.setObjectName("labelPortUserName_3")
        self.horizontalLayout_18.addWidget(self.labelPortUserName_3)
        self.lineEditPortUserName_3 = QtWidgets.QLineEdit(self.layoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPortUserName_3.sizePolicy().hasHeightForWidth())
        self.lineEditPortUserName_3.setSizePolicy(sizePolicy)
        self.lineEditPortUserName_3.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPortUserName_3.setText("")
        self.lineEditPortUserName_3.setObjectName("lineEditPortUserName_3")
        self.horizontalLayout_18.addWidget(self.lineEditPortUserName_3)
        self.layoutWidget_16 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_16.setGeometry(QtCore.QRect(20, 240, 458, 24))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.labelPort_14 = QtWidgets.QLabel(self.layoutWidget_16)
        self.labelPort_14.setMinimumSize(QtCore.QSize(50, 0))
        self.labelPort_14.setObjectName("labelPort_14")
        self.horizontalLayout_23.addWidget(self.labelPort_14)
        self.lineEditPortPassword_3 = QtWidgets.QLineEdit(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPortPassword_3.sizePolicy().hasHeightForWidth())
        self.lineEditPortPassword_3.setSizePolicy(sizePolicy)
        self.lineEditPortPassword_3.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditPortPassword_3.setText("")
        self.lineEditPortPassword_3.setObjectName("lineEditPortPassword_3")
        self.horizontalLayout_23.addWidget(self.lineEditPortPassword_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1065, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DIAGNOSTICOS INTELIGENTES: Cliente IOT-DB"))
        self.groupBox.setTitle(_translate("MainWindow", "Conexion al Servidor IOT"))
        self.pushButtonConnectIOT.setText(_translate("MainWindow", "Reconectar IOT"))
        self.labelHost.setText(_translate("MainWindow", "host"))
        self.lineEditHostIOT.setText(_translate("MainWindow", "broker.mqttdashboard.com"))
        self.labelPort.setText(_translate("MainWindow", "port"))
        self.lineEditPortIOT.setText(_translate("MainWindow", "1883"))
        self.labelPortClientId.setText(_translate("MainWindow", "clientId"))
        self.lineEditPortClientId.setText(_translate("MainWindow", "Usuario - MAC"))
        self.labelPortUserName.setText(_translate("MainWindow", "Usuario"))
        self.labelPort_12.setText(_translate("MainWindow", "Contraseña"))
        self.checkBoxCleanSession.setText(_translate("MainWindow", "CleanSession"))
        self.checkBoxAutoConnect.setText(_translate("MainWindow", "auto connect"))
        self.labelPortKeepAlive.setText(_translate("MainWindow", "keep alive(S)"))
        self.labelTopicSub.setText(_translate("MainWindow", "topic"))
        self.comboBoxSubTopics.setItemText(0, _translate("MainWindow", "solutia/iot/anamot/#"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Mensajes recibidos y Guardados"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Conexion al Servidor DB"))
        self.pushButtonConnectDB.setText(_translate("MainWindow", "Reconectar DB"))
        self.labelHost_3.setText(_translate("MainWindow", "host"))
        self.lineEditHostDB.setText(_translate("MainWindow", "proyectomotores-1xti3.mongodb.net/test?retryWrites=true&w=majority"))
        self.labelPort_3.setText(_translate("MainWindow", "port"))
        self.lineEditPortDB.setText(_translate("MainWindow", "27017"))
        self.labelPortClientId_3.setText(_translate("MainWindow", "clientId"))
        self.lineEditPortClientId_3.setText(_translate("MainWindow", "Usuario - MAC"))
        self.labelPortUserName_3.setText(_translate("MainWindow", "Usuario"))
        self.lineEditPortUserName_3.setText(_translate("MainWindow", "danieluranga"))
        self.labelPort_14.setText(_translate("MainWindow", "Contraseña"))
        self.lineEditPortPassword_3.setText(_translate("MainWindow", "eV4633R9AZVF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
